# Linear Regration 
 Linear regression is also a type of machine-learning algorithm more specifically a supervised machine-learning algorithm that learns from the labelled datasets and maps the data points to the most optimized linear functions. which can be used for prediction on new datasets.
 * Labeled data means the dataset whose respective target value is already known
### Classification: 
It predicts the class of the dataset based on the independent input variable. Class is the categorical or discrete values. like the image of an animal is a cat or dog?
### Regression:
 It predicts the continuous output variables based on the independent input variable. like the prediction of house prices based on different parameters like house age, distance from the main road, location, area, etc.

## Table of Content

* What is Linear Regression?
* Types of Linear Regression
* What is the best Fit Line?
* Cost function for Linear Regression
* Assumptions of Simple Linear Regression
* Assumptions of Multiple Linear Regression
* Evaluation Metrics for Linear Regression
* Python Implementation of Linear Regression
* Regularization Techniques for Linear Models
* Applications of Linear Regression
* Advantages & Disadvantages of Linear Regression
* Linear Regression – Frequently Asked Questions (FAQs)

#### The most common measurements are:
* Mean Square Error (MSE)
MSE= 
n1∑i=1n(yi–yi)**2
  * n is the number of data points.
    * yi is the actual or observed value for the ith data point.
    * ^yi is the predicted value for the ith data point.
* Mean Absolute Error (MAE)

In [1]:
#Python Implementation of Linear Regression
# Import the necessary libraries:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# read the read from file 
dimonds_df = pd.read_csv('Diamonds Prices2022.csv')
dimonds_df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64
53940,53941,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49
53941,53942,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43
53942,53943,0.70,Very Good,E,VS2,60.5,59.0,2757,5.71,5.76,3.47

In [3]:
# Drop the missing values
dimonds_df.dropna()
# df.isnull().sum()
dimonds_df.info() # find the information of this data 
dimonds_df.shape  # shape of data set 
dimonds_df=dimonds_df.select_dtypes(include='O') # so first upon we are find object value 
dimonds_df
dimonds_df=dimonds_df.select_dtypes(exclude='O') # so first upon we are find numerical value 
dimonds_df

dimonds_df['color'].unique() 
dimonds_df_colour_dt = {'E':0,'I':1,'J':2,'H':3,'F':4,'G':5,'D':6}
dimonds_df['color']=dimonds_df['color'].map(dimonds_df_colour_dt)
dimonds_df['clarity'].unique()
dimonds_df_cal_clarity_dt = {'SI2':0, 'SI1':1, 'VS1':2, 'VS2':3, 'VVS2':4, 'VVS1':5, 'I1':6, 'IF':7}
dimonds_df['clarity']=dimonds_df['clarity'].map(dimonds_df_cal_clarity_dt)
dimonds_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53943 entries, 0 to 53942
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53943 non-null  int64
 1   carat       53943 non-null  float64
 2   cut         53943 non-null  object
 3   color       53943 non-null  object
 4   clarity     53943 non-null  object
 5   depth       53943 non-null  float64
 6   table       53943 non-null  float64
 7   price       53943 non-null  int64
 8   x           53943 non-null  float64
 9   y           53943 non-null  float64
 10  z           53943 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB

KeyError: 'color'

In [ ]:
dimonds_df['cut'].unique() # find the unique value of a particular feartures

dimonds_df_cal_cut_dt = {'Ideal':0,'Premium':1,'Good':2,'Very Good':3,'Fair':4}
dimonds_df['cut']=dimonds_df['cut'].map(dimonds_df_cal_cut_dt)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,0,0,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,0,1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,0,2,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,1,3,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,2,0,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53938,53939,0.86,Premium,3,0,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,6,0,62.2,55.0,2757,5.83,5.87,3.64
53940,53941,0.71,Premium,0,1,60.5,55.0,2756,5.79,5.74,3.49
53941,53942,0.71,Premium,4,1,59.8,62.0,2756,5.74,5.73,3.43
53942,53943,0.70,Very Good,0,3,60.5,59.0,2757,5.71,5.76,3.47

In [ ]:
matrix = dimonds_df.corr()
matrix

ValueError: could not convert string to float: 'Ideal'