# linear Regration

first upon we are import of this library

In [265]:
import pandas  as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

then we are read of data

In [266]:
laptop_df= pd.read_csv('laptopPrice.csv')
laptop_df # create a variable

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [267]:
laptop_df.isnull().sum() # so we are find null value in df

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [268]:
laptop_df.duplicated().sum() # then after we are find duplicated value

21

In [269]:
laptop_df.drop_duplicates(inplace=True) # so we are drop of duplicate value in data fram

In [270]:
laptop_df.shape # find the shape of datafram by using shape function

(802, 19)

In [271]:
laptop_df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [272]:
laptop_df['brand'].unique()
dt_brand ={"ASUS":1, "Lenovo":2, "acer":3, "Avita":4, "HP":5, "DELL":6, "MSI":7, "APPLE":8}
laptop_df['brand']=laptop_df['brand'].map(dt_brand)

In [273]:
laptop_df['os'].unique()
dt_os = {"Windows":0,"DOS":1,"Mac":2}
laptop_df['os']=laptop_df['os'].map(dt_os)

In [274]:
laptop_df['hdd'].unique()
dt_hdd={"1024 GB":1024,"0 GB":0,"512 GB":512,"2048 GB":2048}
laptop_df['hdd']=laptop_df['hdd'].map(dt_hdd)

In [275]:
laptop_df['msoffice'].unique()
dt_ms={"No":0,"Yes":1}
laptop_df['msoffice']=laptop_df['msoffice'].map(dt_ms)

In [276]:
laptop_df['ssd'].unique()
dt_ssd = {"0 GB":1,"512 GB":512,"256 GB":256,"128 GB":128,"1024 GB":1024,"2048 GB":2048,"3072 GB":3072}
laptop_df['Touchscreen']=laptop_df['Touchscreen'].map(dt_ssd)

In [277]:
laptop_df['Touchscreen'].unique()
dt_touch = {"No":0,"Yes":1}
laptop_df['Touchscreen']=laptop_df['Touchscreen'].map(dt_touch)

In [278]:
laptop_df['graphic_card_gb'].unique()
dt_graphic = {"0 GB":0,"2 GB":2,"4 GB":4,"6 GB":6,"8 GB":8}
laptop_df['graphic_card_gb']=laptop_df['graphic_card_gb'].map(dt_graphic)

In [279]:
laptop_df['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [280]:
laptop_df['ram_gb'].unique()
dt_ram = {"4 GB":4,"8 GB":8,"16 GB":16,"32 GB":32}
laptop_df['ram_gb'] = laptop_df['ram_gb'].map(dt_ram)

In [281]:
laptop_df['os_bit'].unique()
laptop_df['os_bit'].value_counts()
dit = {"64-bit":6,"32-bit":3}
laptop_df['os_bit']=laptop_df['os_bit'].map(dit)

In [282]:
laptop_df['processor_brand'].unique()
laptop_df['processor_brand'].value_counts()

processor_brand
Intel    594
AMD      189
M1        19
Name: count, dtype: int64

In [283]:
dt={"Intel":1,"AMD":2,"M1":3}
dt

{'Intel': 1, 'AMD': 2, 'M1': 3}

In [284]:
laptop_df['processor_brand']= laptop_df['processor_brand'].map(dt)
laptop_df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,Core i3,10th,4,DDR4,0 GB,1024,0,6,0,Casual,No warranty,NaN,0,34649,2 stars,3,0
1,2,1,Core i3,10th,4,DDR4,0 GB,1024,0,6,0,Casual,No warranty,NaN,0,38999,3 stars,65,5
2,2,1,Core i3,10th,4,DDR4,0 GB,1024,0,6,0,Casual,No warranty,NaN,0,39999,3 stars,8,1
3,1,1,Core i5,10th,8,DDR4,512 GB,0,0,3,2,Casual,No warranty,NaN,0,69990,3 stars,0,0
4,1,1,Celeron Dual,Not Available,4,DDR4,0 GB,512,0,6,0,Casual,No warranty,NaN,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,Not Available,4,DDR4,1024 GB,0,0,6,0,Casual,1 year,NaN,0,135990,3 stars,0,0
819,1,2,Ryzen 9,Not Available,4,DDR4,1024 GB,0,0,6,0,Casual,1 year,NaN,0,144990,3 stars,0,0
820,1,2,Ryzen 9,Not Available,4,DDR4,1024 GB,0,0,6,4,Casual,1 year,NaN,0,149990,3 stars,0,0
821,1,2,Ryzen 9,Not Available,4,DDR4,1024 GB,0,0,6,4,Casual,1 year,NaN,0,142990,3 stars,0,0
822,2,2,Ryzen 5,10th,8,DDR4,512 GB,0,1,6,0,ThinNlight,No warranty,NaN,0,57490,4 stars,18,4

In [285]:
laptop_df['ssd'].unique()
dt_ssd = {"0 GB":0,"512 GB":512,"256 GB":256,"1024 GB":1024,"2048 GB":2048,"3072 GB":3072,}
laptop_df['ssd']=laptop_df['ssd'].map(dt_ssd)

In [286]:
cal_df=laptop_df.select_dtypes(include='O') # esme apn catcorikal value ko alg kr rhe hai
cal_df

    processor_name processor_gnrtn ram_type      weight     warranty   rating
0          Core i3            10th     DDR4      Casual  No warranty  2 stars
1          Core i3            10th     DDR4      Casual  No warranty  3 stars
2          Core i3            10th     DDR4      Casual  No warranty  3 stars
3          Core i5            10th     DDR4      Casual  No warranty  3 stars
4     Celeron Dual   Not Available     DDR4      Casual  No warranty  3 stars
..             ...             ...      ...         ...          ...      ...
818        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
819        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
820        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
821        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
822        Ryzen 5            10th     DDR4  ThinNlight  No warranty  4 stars

[802 rows x 6 columns]

In [287]:
laptop_df['processor_name'].unique()
dt_processor_name = {"Core i3":13,"Core i5":15,"Celeron Dual":0,"Ryzen 5":5,"Core i7":17,"Core i9":19,"M1":00,"Pentium Quad":000,"Ryzen 3":3,"Ryzen 7":7,"Ryzen 9":9}
laptop_df['processor_name']=laptop_df['processor_name'].map(dt_processor_name)

In [288]:
num_col = laptop_df.select_dtypes(exclude='O') # esme apn numerical value vale coloum alg kr liye 
num_col

,brand,processor_brand,processor_name,ram_gb,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,msoffice,Price,Number of Ratings,Number of Reviews
0,1,1,13,4,0.0,1024,0,6,0,NaN,0,34649,3,0
1,2,1,13,4,0.0,1024,0,6,0,NaN,0,38999,65,5
2,2,1,13,4,0.0,1024,0,6,0,NaN,0,39999,8,1
3,1,1,15,8,512.0,0,0,3,2,NaN,0,69990,0,0
4,1,1,0,4,0.0,512,0,6,0,NaN,0,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,9,4,1024.0,0,0,6,0,NaN,0,135990,0,0
819,1,2,9,4,1024.0,0,0,6,0,NaN,0,144990,0,0
820,1,2,9,4,1024.0,0,0,6,4,NaN,0,149990,0,0
821,1,2,9,4,1024.0,0,0,6,4,NaN,0,142990,0,0
822,2,2,5,8,512.0,0,1,6,0,NaN,0,57490,18,4

In [289]:
laptop_df['brand'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [290]:
cal_df

    processor_name processor_gnrtn ram_type      weight     warranty   rating
0          Core i3            10th     DDR4      Casual  No warranty  2 stars
1          Core i3            10th     DDR4      Casual  No warranty  3 stars
2          Core i3            10th     DDR4      Casual  No warranty  3 stars
3          Core i5            10th     DDR4      Casual  No warranty  3 stars
4     Celeron Dual   Not Available     DDR4      Casual  No warranty  3 stars
..             ...             ...      ...         ...          ...      ...
818        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
819        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
820        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
821        Ryzen 9   Not Available     DDR4      Casual       1 year  3 stars
822        Ryzen 5            10th     DDR4  ThinNlight  No warranty  4 stars

[802 rows x 6 columns]

In [295]:
cal_df.drop(['weight','warranty','rating'],axis='columns')

KeyError: "['weight', 'warranty', 'rating'] not found in axis"

In [292]:
num_col

,brand,processor_brand,processor_name,ram_gb,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,msoffice,Price,Number of Ratings,Number of Reviews
0,1,1,13,4,0.0,1024,0,6,0,NaN,0,34649,3,0
1,2,1,13,4,0.0,1024,0,6,0,NaN,0,38999,65,5
2,2,1,13,4,0.0,1024,0,6,0,NaN,0,39999,8,1
3,1,1,15,8,512.0,0,0,3,2,NaN,0,69990,0,0
4,1,1,0,4,0.0,512,0,6,0,NaN,0,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,9,4,1024.0,0,0,6,0,NaN,0,135990,0,0
819,1,2,9,4,1024.0,0,0,6,0,NaN,0,144990,0,0
820,1,2,9,4,1024.0,0,0,6,4,NaN,0,149990,0,0
821,1,2,9,4,1024.0,0,0,6,4,NaN,0,142990,0,0
822,2,2,5,8,512.0,0,1,6,0,NaN,0,57490,18,4